from fpdf import FPDF
import datetime
import json


# ── Utility helpers ────────────────────────────────────────────────────────────

# Characters that look like latin-1 equivalents
_UNICODE_MAP = str.maketrans({
    '\u2019': "'",   # right single quotation mark
    '\u2018': "'",   # left single quotation mark
    '\u201c': '"',   # left double quotation mark
    '\u201d': '"',   # right double quotation mark
    '\u2013': '-',   # en dash
    '\u2014': '-',   # em dash
    '\u2022': '-',   # bullet
    '\u2026': '...', # ellipsis
    '\u00e2': 'a',   # a with circumflex
    '\u00e9': 'e',   # e with acute
    '\u00e8': 'e',   # e with grave
    '\u00e0': 'a',   # a with grave
    '\u00fc': 'u',   # u with umlaut
    '\u00f6': 'o',   # o with umlaut
    '\u00e4': 'a',   # a with umlaut
    '\u2192': '->',  # right arrow
    '\u2713': 'OK',  # check mark
    '\u00b7': '-',   # middle dot
})


def _sanitize(text: str) -> str:
    """Transliterate common unicode to ASCII/latin-1; drop everything else."""
    text = text.translate(_UNICODE_MAP)
    return text.encode('latin-1', errors='replace').decode('latin-1')


def _safe_text(value, fallback="N/A"):
    if value is None:
        return fallback
    text = str(value).strip()
    return _sanitize(text) if text else fallback


def _safe_llm_payload(data):
    llm_output = data.get('llm_output', {})
    if isinstance(llm_output, dict):
        return llm_output
    if isinstance(llm_output, str):
        try:
            parsed = json.loads(llm_output)
            if isinstance(parsed, dict):
                return parsed
        except Exception:
            return {}
    return {}


def _safe_checklist_scan(data):
    scan = data.get('checklist_scan', [])
    if isinstance(scan, list):
        return scan
    if isinstance(scan, str):
        try:
            parsed = json.loads(scan)
            return parsed if isinstance(parsed, list) else []
        except Exception:
            return []
    return []


def _wrap_text(pdf, text, width):
    """Word-wrap text to fit inside `width` (in mm) using the current font."""
    text = _safe_text(text, "")
    if not text:
        return [""]
    words = text.split()
    if not words:
        return [text]

    lines = []
    current_line = words[0]
    for word in words[1:]:
        candidate = f"{current_line} {word}"
        if pdf.get_string_width(candidate) <= width:
            current_line = candidate
        else:
            lines.append(current_line)
            current_line = word
    if current_line:
        lines.append(current_line)
    return lines or [text]


# ── PDF class ──────────────────────────────────────────────────────────────────

MARGIN_L   = 12   # left margin  (mm)
MARGIN_R   = 12   # right margin (mm)
PAGE_W     = 210  # A4 width     (mm)
CONTENT_W  = PAGE_W - MARGIN_L - MARGIN_R  # 186 mm usable


class PDFReport(FPDF):
    def header(self):
        self.set_fill_color(52, 73, 94)
        self.rect(0, 0, PAGE_W, 18, 'F')
        self.set_y(4)
        self.set_font('Arial', 'B', 15)
        self.set_text_color(255, 255, 255)
        self.cell(0, 10, 'Vision Board Resume X Assessment', 0, 1, 'C')
        self.set_text_color(0, 0, 0)
        self.ln(8)

    def footer(self):
        self.set_y(-13)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 8, f'Generated by Vision Board Resume X  |  Page {self.page_no()}', 0, 0, 'C')
        self.set_text_color(0, 0, 0)

    def set_default_margins(self):
        self.set_left_margin(MARGIN_L)
        self.set_right_margin(MARGIN_R)
        self.set_x(MARGIN_L)

    def section_title(self, label):
        self.ln(4)
        self.set_default_margins()
        self.set_font('Arial', 'B', 11)
        self.set_fill_color(232, 236, 240)
        self.set_text_color(30, 30, 30)
        self.cell(CONTENT_W, 8, f"  {label}", 0, 1, 'L', fill=True)
        self.ln(3)
        self.set_default_margins()

    def kv_row(self, label, value, label_w=42):
        """Render a bold-label + normal-value row. Handles long values via multi_cell."""
        self.set_default_margins()
        # Bold label
        self.set_font('Arial', 'B', 10)
        self.cell(label_w, 6, label, 0, 0)
        # Value — use multi_cell so long filenames wrap
        self.set_font('Arial', '', 10)
        self.multi_cell(CONTENT_W - label_w, 6, _safe_text(value))
        self.set_default_margins()

    def _guard_page_break(self, needed_height):
        """Add a new page if there isn't enough room for `needed_height` mm."""
        if self.get_y() + needed_height > self.page_break_trigger:
            self.add_page()
            self.set_default_margins()

    # ── Checklist table row ────────────────────────────────────────────────────
    def render_scan_row(self, status, rule_id, description, details,
                        col_widths, line_height=5):
        status_w, rule_w, text_w = col_widths

        # Build combined text and pre-wrap it
        combined = description if not details or details == "Rule passed" else f"{description}. {details}"
        self.set_font('Arial', '', 8)
        wrapped = _wrap_text(self, combined, text_w - 3)
        row_h = max(len(wrapped), 1) * line_height + 2  # +2 padding

        # Page-break guard
        self._guard_page_break(row_h)

        x0 = MARGIN_L
        y0 = self.get_y()

        # Draw cell borders
        self.rect(x0,                    y0, status_w, row_h)
        self.rect(x0 + status_w,         y0, rule_w,   row_h)
        self.rect(x0 + status_w + rule_w, y0, text_w,  row_h)

        # Status cell (vertically centred, coloured)
        if status == "PASS":
            self.set_text_color(0, 140, 0)
        elif status == "FAIL":
            self.set_text_color(190, 0, 0)
        else:
            self.set_text_color(80, 80, 80)

        cy = y0 + (row_h - line_height) / 2
        self.set_font('Arial', 'B', 8)
        self.set_xy(x0, cy)
        self.cell(status_w, line_height, status, 0, 0, 'C')

        # Rule ID cell (vertically centred, black)
        self.set_text_color(0, 0, 0)
        self.set_font('Arial', '', 7)
        # Truncate rule_id to fit
        self.set_xy(x0 + status_w, cy)
        self.cell(rule_w, line_height, rule_id[:18], 0, 0, 'C')

        # Checklist-item text (left-aligned, multi-line)
        self.set_font('Arial', '', 8)
        self.set_text_color(0, 0, 0)
        tx = x0 + status_w + rule_w + 2
        ty = y0 + 1
        for i, line in enumerate(wrapped):
            self.set_xy(tx, ty + i * line_height)
            self.cell(text_w - 3, line_height, line, 0, 0, 'L')

        self.set_xy(x0, y0 + row_h)


# ── Main generator ─────────────────────────────────────────────────────────────

def generate_pdf_report(data):
    pdf = PDFReport()
    pdf.set_margins(MARGIN_L, 10, MARGIN_R)
    pdf.set_auto_page_break(auto=True, margin=18)
    pdf.add_page()

    # ── Resolve data ───────────────────────────────────────────────────────────
    filename          = _safe_text(data.get('resume_filename_original') or data.get('filename'))
    candidate_name    = _safe_text(data.get('candidate_name'))
    vendor_name       = _safe_text(data.get('vendor_name'))
    checklist_version = _safe_text(data.get('checklist_version_id'))
    rules_score       = round(float(data.get('rules_score',   0.0)), 1)
    llm_score         = round(float(data.get('llm_score',     0.0)), 1)
    stored_overall    = round(float(data.get('overall_score', 0.0)), 1)
    derived_overall   = round((rules_score * 0.4) + (llm_score * 0.6), 1)
    overall_score     = stored_overall if stored_overall > 0 else derived_overall
    llm               = _safe_llm_payload(data)
    checklist_scan    = _safe_checklist_scan(data)
    violations        = data.get('rule_violations', [])

    # ── Candidate info block ───────────────────────────────────────────────────
    info_rows = [
        ("Candidate:",     candidate_name),
        ("Vendor:",        vendor_name),
        ("Filename:",      filename),
        ("Checklist Ver:", checklist_version),
        ("Date:",         datetime.datetime.now().strftime('%Y-%m-%d  %H:%M')),
        ("Rules Score:",  f"{rules_score:.1f} / 100"),
        ("AI Score:",     f"{llm_score:.1f} / 100"),
    ]
    for label, val in info_rows:
        pdf.kv_row(label, val, label_w=42)

    # Score explanation (italic, small)
    pdf.set_default_margins()
    pdf.set_font('Arial', 'I', 9)
    pdf.set_text_color(90, 90, 90)
    pdf.cell(CONTENT_W, 5,
             f"Score formula: 40% checklist + 60% AI quality  |  Overall: {overall_score:.1f}/100",
             0, 1)
    pdf.set_text_color(0, 0, 0)
    pdf.ln(4)

    # ── Overall score banner ───────────────────────────────────────────────────
    banner_y = pdf.get_y()
    if overall_score >= 70:
        fill_color = (46, 174, 100)   # green
    elif overall_score >= 50:
        fill_color = (230, 150, 30)   # amber
    else:
        fill_color = (210, 60, 50)    # red

    pdf.set_fill_color(*fill_color)
    pdf.rect(MARGIN_L, banner_y, CONTENT_W, 18, 'F')
    pdf.set_y(banner_y + 3)
    pdf.set_font('Arial', 'B', 17)
    pdf.set_text_color(255, 255, 255)
    pdf.cell(CONTENT_W, 12, f"OVERALL SCORE:  {overall_score:.1f} / 100", 0, 1, 'C')
    pdf.set_text_color(0, 0, 0)
    pdf.ln(8)

    # ══════════════════════════════════════════════════════════════════════════
    #  SECTION 1 — Eligibility Checklist
    # ══════════════════════════════════════════════════════════════════════════
    pdf.section_title("1. ELIGIBILITY CHECKLIST")

    # Violation summary
    pdf.set_default_margins()
    if not violations:
        pdf.set_font('Arial', 'B', 10)
        pdf.set_text_color(0, 140, 0)
        pdf.cell(CONTENT_W, 7, "[PASS]  All mandatory criteria met.", 0, 1)
    else:
        pdf.set_font('Arial', 'B', 10)
        pdf.set_text_color(190, 0, 0)
        pdf.cell(CONTENT_W, 7, f"[FAIL]  Found {len(violations)} critical violation(s)", 0, 1)
        pdf.ln(1)
        pdf.set_font('Arial', '', 9)
        pdf.set_text_color(50, 50, 50)
        for v in violations:
            msg = _safe_text(v.get('violation_message', ''))
            pdf.set_default_margins()
            pdf.cell(6, 5, "-", 0, 0)
            pdf.set_left_margin(MARGIN_L + 6)
            pdf.multi_cell(CONTENT_W - 6, 5, msg)
            pdf.set_left_margin(MARGIN_L)
            pdf.ln(1)

    pdf.set_text_color(0, 0, 0)
    pdf.ln(3)

    # Checklist table
    if checklist_scan:
        status_w = 20
        rule_w   = 42
        text_w   = CONTENT_W - status_w - rule_w  # 124 mm

        # Header row
        pdf.set_default_margins()
        pdf.set_font('Arial', 'B', 9)
        pdf.set_fill_color(52, 73, 94)
        pdf.set_text_color(255, 255, 255)
        pdf.cell(status_w, 8, "Status",        1, 0, 'C', fill=True)
        pdf.cell(rule_w,   8, "Rule ID",        1, 0, 'C', fill=True)
        pdf.cell(text_w,   8, "Checklist Item", 1, 1, 'C', fill=True)
        pdf.set_text_color(0, 0, 0)

        # Data rows
        for row in checklist_scan:
            status      = str(row.get('status',      'UNKNOWN')).upper()
            rule_id     = _safe_text(row.get('rule_id'),      'N/A')
            description = _safe_text(row.get('description'),  'N/A')
            details     = _safe_text(row.get('details'),       '')
            pdf.render_scan_row(
                status, rule_id, description, details,
                (status_w, rule_w, text_w), line_height=5
            )
    else:
        pdf.set_font('Arial', 'I', 9)
        pdf.cell(CONTENT_W, 6, "Checklist scan details were not available.", 0, 1)

    # ══════════════════════════════════════════════════════════════════════════
    #  SECTION 2 — AI Quality Assessment
    # ══════════════════════════════════════════════════════════════════════════
    pdf.section_title("2. AI QUALITY ASSESSMENT")

    # Section scores table
    scores = llm.get('section_scores', {})
    half_w = CONTENT_W // 2
    pdf.set_default_margins()
    pdf.set_font('Arial', 'B', 10)
    pdf.set_fill_color(232, 236, 240)
    pdf.cell(half_w + 20, 8, "Category",     1, 0, 'C', fill=True)
    pdf.cell(half_w - 20, 8, "Score (0-10)", 1, 1, 'C', fill=True)
    pdf.set_font('Arial', '', 10)
    if scores:
        for sec, val in scores.items():
            pdf.set_default_margins()
            pdf.cell(half_w + 20, 7, f"  {sec}", 1, 0, 'L')
            pdf.cell(half_w - 20, 7, f"{val}/10", 1, 1, 'C')
    else:
        pdf.set_default_margins()
        pdf.cell(CONTENT_W, 7, "Section scores unavailable", 1, 1, 'C')
    pdf.ln(5)

    # ── Strengths & Gaps — stacked layout (no two-column) ─────────────────────
    # Two-column layout in fpdf breaks across page breaks. Use stacked instead.
    pdf.set_default_margins()

    # Strengths
    pdf.set_font('Arial', 'B', 11)
    pdf.set_text_color(0, 120, 50)
    pdf.cell(CONTENT_W, 7, "Key Strengths", 0, 1)
    pdf.set_font('Arial', '', 9)
    pdf.set_text_color(30, 30, 30)
    strengths = llm.get('strengths', [])
    if strengths:
        for s in strengths:
            pdf._guard_page_break(10)
            pdf.set_default_margins()
            pdf.cell(7, 5, "+", 0, 0)  # latin-1 safe
            pdf.set_left_margin(MARGIN_L + 7)
            pdf.multi_cell(CONTENT_W - 7, 5, _safe_text(s))
            pdf.set_left_margin(MARGIN_L)
    else:
        pdf.set_default_margins()
        pdf.set_font('Arial', 'I', 9)
        pdf.cell(CONTENT_W, 5, "No strengths captured.", 0, 1)

    pdf.ln(4)

    # Gaps
    pdf.set_default_margins()
    pdf.set_font('Arial', 'B', 11)
    pdf.set_text_color(190, 0, 0)
    pdf.cell(CONTENT_W, 7, "Identified Gaps", 0, 1)
    pdf.set_font('Arial', '', 9)
    pdf.set_text_color(30, 30, 30)
    gaps = llm.get('gaps', [])
    if gaps:
        for g in gaps:
            pdf._guard_page_break(10)
            pdf.set_default_margins()
            pdf.cell(7, 5, "-", 0, 0)
            pdf.set_left_margin(MARGIN_L + 7)
            pdf.multi_cell(CONTENT_W - 7, 5, _safe_text(g))
            pdf.set_left_margin(MARGIN_L)
    else:
        pdf.set_default_margins()
        pdf.set_font('Arial', 'I', 9)
        pdf.cell(CONTENT_W, 5, "No gaps captured.", 0, 1)

    pdf.set_text_color(0, 0, 0)
    pdf.ln(4)

    # ══════════════════════════════════════════════════════════════════════════
    #  SECTION 3 — Coaching & Improvements
    # ══════════════════════════════════════════════════════════════════════════
    pdf.section_title("3. COACHING & IMPROVEMENTS")

    improvements = llm.get('improvements', [])
    rewrite_suggestions = llm.get('rewrite_suggestions', {})
    if not isinstance(rewrite_suggestions, dict):
        rewrite_suggestions = {}

    if not improvements:
        pdf.set_default_margins()
        pdf.set_font('Arial', 'I', 10)
        pdf.cell(CONTENT_W, 7, "No improvement actions generated.", 0, 1)

    LABEL_W  = 22   # bold label column
    VALUE_W  = CONTENT_W - LABEL_W

    for imp in improvements:
        section  = _safe_text(imp.get('section',    'General'))
        issue    = _safe_text(imp.get('issue',       'N/A'))
        sugg     = _safe_text(imp.get('suggestion',  'N/A'))
        priority = _safe_text(imp.get('priority',    'Medium'))

        # Estimate block height for page-break guard
        pdf._guard_page_break(35)

        # Section
        pdf.set_default_margins()
        pdf.set_font('Arial', 'B', 10)
        pdf.cell(LABEL_W, 6, "Section:", 0, 0, 'L')
        pdf.set_font('Arial', '', 10)
        pdf.cell(VALUE_W, 6, section, 0, 1, 'L')

        # Issue
        pdf.set_default_margins()
        pdf.set_font('Arial', 'B', 10)
        pdf.cell(LABEL_W, 6, "Issue:", 0, 0, 'L')
        pdf.set_font('Arial', '', 10)
        pdf.set_left_margin(MARGIN_L + LABEL_W)
        pdf.multi_cell(VALUE_W, 6, issue)
        pdf.set_left_margin(MARGIN_L)

        # Priority
        prio_color = {
            'High':   (205, 60,  50),
            'Medium': (200, 130,  0),
            'Low':    (50,  150, 50),
        }.get(priority, (60, 60, 60))
        pdf.set_default_margins()
        pdf.set_font('Arial', 'B', 10)
        pdf.cell(LABEL_W, 6, "Priority:", 0, 0, 'L')
        pdf.set_font('Arial', '', 10)
        pdf.set_text_color(*prio_color)
        pdf.cell(VALUE_W, 6, priority, 0, 1, 'L')
        pdf.set_text_color(0, 0, 0)

        # Fix / suggestion
        pdf.set_default_margins()
        pdf.set_font('Arial', 'B', 10)
        pdf.cell(LABEL_W, 6, "Fix:", 0, 0, 'L')
        pdf.set_font('Arial', 'I', 10)
        pdf.set_text_color(20, 60, 160)
        pdf.set_left_margin(MARGIN_L + LABEL_W)
        pdf.multi_cell(VALUE_W, 6, sugg)
        pdf.set_left_margin(MARGIN_L)
        pdf.set_text_color(0, 0, 0)

        # Rewrite suggestion (if any)
        rewrite = rewrite_suggestions.get(section) or rewrite_suggestions.get(section.lower())
        if rewrite:
            pdf._guard_page_break(20)
            pdf.set_default_margins()
            pdf.set_font('Arial', 'B', 10)
            pdf.cell(LABEL_W, 6, "Rewrite:", 0, 0, 'L')
            pdf.set_font('Arial', '', 9)
            pdf.set_text_color(40, 40, 40)
            pdf.set_left_margin(MARGIN_L + LABEL_W)
            pdf.multi_cell(VALUE_W, 6, _safe_text(rewrite))
            pdf.set_left_margin(MARGIN_L)
            pdf.set_text_color(0, 0, 0)

        # Divider line
        pdf.ln(3)
        pdf.set_draw_color(200, 200, 200)
        pdf.line(MARGIN_L, pdf.get_y(), PAGE_W - MARGIN_R, pdf.get_y())
        pdf.set_draw_color(0, 0, 0)
        pdf.ln(4)

    return pdf.output(dest='S').encode('latin-1', errors='replace')
